language: node_js
sudo: false
node_js:
  - 0.12

before_script:
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter

after_success:
  - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN codeclimate < ./coverage/lcov.info

deploy:
  provider: npm
  email: thaiat@ipelia.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
    repo: thaiat/generator-angular-famous-ionic
